#Create Deployment file 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-test
 labels:
  name: myapp
  type: frontend
spec:
 template:
  metadata:
   name: myapp
   labels:
    name: myapp
    type: frontend
  spec:
   containers:
    - name: nginx-contaioner
      image: nginx 
      resources:
       limits:
        memory: "128Mi"
        cpu: "250m"
 replicas: 2
 selector:
  matchLabels:
   type: frontend