apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
  labels:
    app: my-app
    type: front-end
spec:
  containers:
  - name: myapp
    image: nginx
    command : ["sleep"]
    args: ["10"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "120M"

