apiVersion: apps/v1
kind: Deployment 
metadata:
 name: postgres-app-deploy
 labels:
  name: postgres-app-deploy
  app: demo-voting-app
spec:
 template:
  metadata:
   name: postgres-test
   labels:
    app: postgres-test
    type: front-end
  spec:
   containers:
   - name: postgres
     image: postgres
     resources:
      limits:
       memory: "128Mi"
       cpu: "500m"
     ports:
     - containerPort: 5432
     env:
     - name: POSTGRE_USER
       value: "postgres"
     - name: POSTGRES_PASSWORD
       value: "postgres"

 replicas: 1
 selector:
   matchLabels:
    app: postgres-test
    type: front-end
    

