apiVersion: apps/v1
kind: Deployment 
metadata:
 name: redis-app-deploy
 labels:
  name: redis-app-deploy
  app: demo-voting-app
spec:
 template:
  metadata:
   name: redis-test
   labels:
    app: redis-test
    type: front-end
  spec:
   containers:
   - name: redis-app
     image: kodekloud/exampleredisapp_vote:v1
     resources:
      limits:
       memory: "128Mi"
       cpu: "500m"
     ports:
     - containerPort: 80

 replicas: 1
 selector:
   matchLabels:
    type: front-end
    app: redis-test

