apiVersion: apps/v1
kind: Deployment 
metadata:
 name: voting-app-deploy
 labels:
  name: voting-app-deploy
  app: demo-voting-app
spec:
 template:
  metadata:
   name: voting-test
   labels:
    app: voting-test
    type: front-end
  spec:
   containers:
   - name: voting-app
     image: kodekloud/examplevotingapp_vote:v1
     resources:
      limits:
       memory: "128Mi"
       cpu: "500m"
     ports:
      - containerPort: 80

 replicas: 1
 selector:
   matchLabels:
    type: front-end
    app: voting-test

