apiVersion: apps/v1
kind: Deployment 
metadata:
 name: worker-app-deploy
 labels:
  name: worker-app-deploy
  app: demo-voting-app
spec:
 template:
  metadata:
   name: worker-test
   labels:
    app: worker-test
    type: front-end
  spec:
   containers:
   - name: worker
     image: worker
     resources:
      limits:
       memory: "128Mi"
       cpu: "500m"
     ports:
     - containerPort: 5432
     env:
     - name: POSTGRE_USER
       value: "worker"
     - name: worker_PASSWORD
       value: "worker"

 replicas: 1
 selector:
   matchLabels:
    app: worker-test
    type: front-end 

